[package]
name = "svg_to_ico"
version = "1.0.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
description = "A utility and Rust library to convert SVG icons into Windows ICO files."
documentation = "https://docs.rs/svg_to_ico"
repository = "https://github.com/WrinklyNinja/svg_to_ico.git"
readme = "README.md"
license = "MIT"
exclude = [
    "target/*",
]

[badges]
appveyor = { repository = "WrinklyNinja/svg_to_ico" }
travis-ci = { repository = "WrinklyNinja/svg_to_ico" }

[dependencies]
clap = "2"
ico = "0.1.0"
nsvg = "0.4"

[dev-dependencies]
tempfile = "3"
