
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.svg_to_ico]
audit-as-crates-io = false

[[exemptions.anstream]]
version = "0.6.18"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.byteorder-lite]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.47"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.47"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.data-url]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.10"
criteria = "safe-to-run"

[[exemptions.float-cmp]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.fontconfig-parser]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.fontdb]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.gif]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.ico]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.image-webp]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.imagesize]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.kurbo]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.9.2"
criteria = "safe-to-run"

[[exemptions.memmap2]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.pico-args]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-run"

[[exemptions.resvg]]
version = "0.45.1"
criteria = "safe-to-deploy"

[[exemptions.rgb]]
version = "0.8.34"
criteria = "safe-to-deploy"

[[exemptions.roxmltree]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.roxmltree]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.rustybuzz]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.simplecss]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.slotmap]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.strict-num]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.svgtypes]]
version = "0.15.3"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.22.0"
criteria = "safe-to-run"

[[exemptions.tiny-skia]]
version = "0.11.4"
criteria = "safe-to-deploy"

[[exemptions.tiny-skia-path]]
version = "0.11.4"
criteria = "safe-to-deploy"

[[exemptions.ttf-parser]]
version = "0.25.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi-mirroring]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ccc]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-properties]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.unicode-script]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.unicode-vo]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.usvg]]
version = "0.45.1"
criteria = "safe-to-deploy"

[[exemptions.weezl]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.xmlparser]]
version = "0.13.5"
criteria = "safe-to-deploy"

[[exemptions.xmlwriter]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.zune-core]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.zune-jpeg]]
version = "0.4.13"
criteria = "safe-to-deploy"
